---
pipeline:
   build_image:
    environment:
      - DOCKER_USERNAME=regt-build-bot
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/rt/mongo:3.2-rt
    secrets: [ DOCKER_PASSWORD ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push
      branch: acp

  build_image_tag:
    environment:
      - DOCKER_USERNAME=regt-build-bot
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/rt/mongo:3.2-rt
    secrets: [ DOCKER_PASSWORD ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag

services:
  database:
      image: mongo